# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('movie_year', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('cast', models.CharField(max_length=100)),
                ('movie_logo', models.FileField(upload_to='')),
            ],
        ),
    ]
