# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='Hollywood',
        ),
    ]
