# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_hollywood_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hollywood',
            old_name='photo',
            new_name='SS',
        ),
    ]
