# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_hollywood_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hollywood',
            name='MP_four',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='MP_four_Link',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='dtsEight_p',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='dtsEight_p_Link',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='dtsSeven_p',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='dtsSeven_p_Link',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='oneEight_p',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='oneEight_p_Link',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='seven_p',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='seven_p_Link',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
