# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20170720_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='hollywood',
            name='MP_fourSize',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='dtsEight_pSize',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='dtsSeven_pSize',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='oneEight_pSize',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='seven_pSize',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
