# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20170720_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hollywood',
            name='description',
            field=models.TextField(),
        ),
    ]
