# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20170720_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hollywood',
            name='MP_four',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='MP_fourSize',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='MP_four_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='dtsEight_p',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='dtsEight_pSize',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='dtsEight_p_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='dtsSeven_p',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='dtsSeven_pSize',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='oneEight_p',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='oneEight_pSize',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='oneEight_p_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='seven_p',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='seven_pSize',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='seven_p_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
