# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20170720_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hollywood',
            name='dtsSeven_p_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
