# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20170721_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hollywood',
            name='movie_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
