# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20170721_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hollywood',
            name='movie_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
