# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20170721_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hollywood',
            name='MP_four_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='dtsEight_p_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='dtsSeven_p_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='oneEight_p_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='seven_p_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
