# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20170721_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='hollywood',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
