# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_auto_20170721_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='hollywood',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
