# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_auto_20170722_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hollywood',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='hollywood',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hollywood',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
