# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_auto_20170725_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hollywood',
            new_name='Movies',
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-created', '-update']},
        ),
    ]
