# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_auto_20170729_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torrents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=350, null=True)),
                ('torrent_size', models.CharField(blank=True, max_length=350, null=True)),
                ('torrent_Link', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='MP_four',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='MP_fourSize',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='MP_four_Link',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='dtsEight_p',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='dtsEight_pSize',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='dtsEight_p_Link',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='dtsSeven_p',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='dtsSeven_pSize',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='dtsSeven_p_Link',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='oneEight_p',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='oneEight_pSize',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='oneEight_p_Link',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='seven_p',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='seven_pSize',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='seven_p_Link',
        ),
        migrations.AddField(
            model_name='torrents',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movies'),
        ),
    ]
