# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0029_auto_20170826_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='BollyTorrents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=350, null=True)),
                ('torrent_size', models.CharField(blank=True, max_length=350, null=True)),
                ('torrent_Link', models.FileField(blank=True, null=True, upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.BollyMovies')),
            ],
        ),
        migrations.AlterField(
            model_name='torrents',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movies'),
        ),
    ]
