# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0030_auto_20170826_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bollytorrents',
            name='movie',
        ),
        migrations.DeleteModel(
            name='BollyMovies',
        ),
        migrations.DeleteModel(
            name='BollyTorrents',
        ),
    ]
