# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0035_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='BollyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_rating', models.CharField(max_length=10, null=True)),
                ('description', models.TextField()),
                ('cast', models.CharField(max_length=100)),
                ('youTrailer_link', models.CharField(max_length=10000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created', '-update'],
            },
        ),
        migrations.CreateModel(
            name='BollyTorrents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=350, null=True)),
                ('torrent_size', models.CharField(blank=True, max_length=350, null=True)),
                ('torrent_Link', models.FileField(blank=True, null=True, upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.BollyDetail')),
            ],
        ),
        migrations.CreateModel(
            name='HollyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_rating', models.CharField(max_length=10, null=True)),
                ('description', models.TextField()),
                ('cast', models.CharField(max_length=100)),
                ('youTrailer_link', models.CharField(max_length=10000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created', '-update'],
            },
        ),
        migrations.CreateModel(
            name='HollyTorrents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=350, null=True)),
                ('torrent_size', models.CharField(blank=True, max_length=350, null=True)),
                ('torrent_Link', models.FileField(blank=True, null=True, upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.HollyDetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='torrents',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movie_rating',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='youTrailer_link',
        ),
        migrations.DeleteModel(
            name='Torrents',
        ),
        migrations.AddField(
            model_name='hollydetail',
            name='holly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movies'),
        ),
        migrations.AddField(
            model_name='bollydetail',
            name='bolly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movies'),
        ),
    ]
