# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0037_auto_20170904_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bollywood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hollywood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='country',
        ),
        migrations.AddField(
            model_name='hollywood',
            name='holly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movies'),
        ),
        migrations.AddField(
            model_name='bollywood',
            name='bolly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movies'),
        ),
    ]
