# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0040_hollywood_torrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrents',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='hollywood',
            name='torrent',
        ),
        migrations.AddField(
            model_name='movies',
            name='file_type',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='torrent_Link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movies',
            name='torrent_size',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.DeleteModel(
            name='Torrents',
        ),
    ]
